apiVersion: apps/v1
kind: Deployment
metadata:
  name: caculator
  namespace: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caculator
  template:
    metadata:
      labels:
        app: caculator
    spec:
      containers:
      - name: caculator
        image: muhammadgalih/caculator-web
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-caculator
  namespace: testing
spec:
  selector:
    app: caculator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
