apiVersion: v1
kind: Namespace
metadata:
  name: apps-caculator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caculator
  template:
    metadata:
      labels:
        app: caculator
    spec:
      containers:
      - name: caculator
        image: registry-nexus.cloud/apps-caculator:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: admin-repo
---
apiVersion: v1
kind: Service
metadata:
  name: svc-caculator
spec:
  selector:
    app: caculator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
